trigger:
  branches:
    include:
    - main
    - develop
    - feature/*
    - release/*
  paths:
    include:
    - src/*           # Trigger when source code changes
    - tests/readyapi/* # Trigger when test files change
    exclude:
    - docs/*          # Don't trigger for documentation changes
    - README.md

pool:
  vmImage: 'windows-latest'  # Use Windows for ReadyAPI/TestEngine

steps:
- checkout: self
  displayName: 'Checkout Repository'

- task: SoapUIProForAzureDevOpsTask@2
  inputs:
    testRunnerPath: 'C:\Program Files\SmartBear\ReadyAPI-3.61.0\bin\testrunner.bat'
    project: 'https://github.com/domcrosbie22/StockDemo/tree/main/'
    rootFolder: '$(Common.TestResultsDirectory)'
    testSuite: 'Data-driven-Test'
    testCase: 'Day-Trading-Warnings'
    authenticationMethod: 'anonymous'

# - task: TestEngine@1
#   inputs:
#     filePath: '
#     testType: 'functionalTest'
#     testSuiteName: 'Data driven Test'
#     testCaseName: 'Day Trading Warnings'
#     serverUrl: 'http://localhost:8080'
#     serverUsername: 'admin'
#     serverPassword: 'password'

